#!/usr/bin/env python3
"""
Crisis-window stress tester for the volume-facility product.

Replays the exact pair-life mechanics over named historical windows
and reports detailed P&L, trigger geometry, and worst-pair outcomes.

Coverage:
  - March 2020 COVID crash      (uses synthetic IV proxy; pre-DVOL)
  - May 2021 China-ban cascade  (DVOL available)
  - June 2022 Luna/UST aftermath
  - November 2022 FTX collapse
  - March 2023 US banking crisis
  - August 2024 yen-carry unwind

For windows where Deribit DVOL is unavailable (pre-2021-04), the
implied vol is approximated as `1.15 × trailing_30d_realized_vol`,
matching the typical empirical implied/realized ratio observed in the
2021-2026 sample.

Outputs:
  docs/cfo-report/double-barrier-analysis/historical/stress_windows.json
  docs/cfo-report/double-barrier-analysis/historical/stress_windows.md
"""

from __future__ import annotations

import csv
import json
import math
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

import simulator as sim
import historical_replay as hr


WINDOWS = [
    ("covid_2020",        "2020-03-01", "2020-04-01", "March 2020 COVID crash"),
    ("china_ban_2021",    "2021-05-08", "2021-06-15", "May 2021 China crackdown / Tesla halt"),
    ("luna_aftermath_22", "2022-05-01", "2022-07-15", "May-July 2022 Luna/UST + 3AC contagion"),
    ("ftx_2022",          "2022-11-01", "2022-12-15", "November 2022 FTX collapse"),
    ("banking_2023",      "2023-03-01", "2023-04-01", "March 2023 US banking crisis (SVB/Signature)"),
    ("yen_carry_2024",    "2024-08-01", "2024-08-15", "August 2024 yen-carry unwind"),
]


def synthetic_iv(rv_30d: float) -> float:
    """1.15 × 30d realized vol; matches the empirical mean implied/realized
    ratio over our 2021-2026 sample."""
    return rv_30d * 1.15


def realized_vol_30d(px_window: np.ndarray) -> float:
    """Annualized realized vol from hourly closes."""
    if len(px_window) < 2:
        return 0.5
    log_ret = np.diff(np.log(px_window))
    return float(np.std(log_ret) * math.sqrt(24 * 365))


def main() -> None:
    print("Loading historical data ...")
    ts, px = hr.load_btc_hourly()
    dvol_map = hr.load_dvol_daily()
    print(f"  {len(px)} BTC hourly bars, {len(dvol_map)} DVOL days")

    PAIR_DAYS = 7
    BARRIER = 0.02
    PAYOUT = 1_000.0
    NOTIONAL = 50_000.0
    RFR = 0.05
    SPREAD = 50.0

    SCHEDULES = {
        "tiered_400_600_900": "tiered_400_600_900",
        "flat_500_under_65": None,  # special
        "tiered_with_stress_1100": None,  # special
    }

    out: dict = {"windows": []}
    md_lines: list[str] = []
    P = md_lines.append

    P("# Crisis-Window Stress Test — Empirical P&L\n")
    P("> Generated by `scripts/double-barrier/stress_window_replay.py`.\n")
    P("> Replays the proposed double-2% barrier product over named "
      "historical crisis windows. P&L is per-pair-life (one trader pair, "
      "$50k each side, 7-day cap, $1k capped payout). For windows before "
      "Deribit DVOL launched (April 2021), implied vol uses the proxy "
      "`1.15 × 30d_realized_vol`.\n")
    P("Three premium schedules tested:\n")
    P("- **T1: tiered $400/$600/$900** (current proposal)")
    P("- **T2: tiered $400/$600/$900/$1,100** (4-tier; adds DVOL≥80 stress band)")
    P("- **T3: flat $500/side for DVOL<65, $900 for ≥65** (simpler 2-tier)\n")

    instrument = "daily_strangle"

    for slug, start_d, end_d, desc in WINDOWS:
        start_ts = int(datetime.strptime(start_d, "%Y-%m-%d")
                       .replace(tzinfo=timezone.utc).timestamp())
        end_ts = int(datetime.strptime(end_d, "%Y-%m-%d")
                     .replace(tzinfo=timezone.utc).timestamp())
        if end_ts > ts[-1]:
            end_ts = int(ts[-1])
        if start_ts < ts[0]:
            print(f"[skip] {slug}: start {start_d} before tape start")
            continue
        idx_start = int(np.searchsorted(ts, start_ts))
        idx_end = int(np.searchsorted(ts, end_ts))
        starts = list(range(idx_start, idx_end - PAIR_DAYS * 24, 24))
        if not starts:
            continue

        print(f"\n=== {desc}  [{start_d} -> {end_d}, {len(starts)} pair starts] ===")
        P(f"\n## {desc}\n")
        P(f"**Window:** {start_d} → {end_d}    "
          f"**Pair starts evaluated:** {len(starts)}    "
          f"**BTC range:** ${px[idx_start]:,.0f} → ${px[idx_end]:,.0f} "
          f"({(px[idx_end]/px[idx_start]-1)*100:+.1f}%)")

        wd = {"slug": slug, "desc": desc, "start": start_d, "end": end_d,
              "n_pair_starts": len(starts), "btc_start": float(px[idx_start]),
              "btc_end": float(px[idx_end]),
              "schedules": {}}

        for sched_label, sched_call in [
            ("T1_tiered_400_600_900", "tiered_400_600_900"),
            ("T2_tiered_w_stress_1100", "tiered_with_stress_1100"),
            ("T3_flat_500_900", "flat_500_900"),
        ]:
            results = []
            triggers_list = []
            for s in starts:
                # Determine implied vol for the pair-open day
                day_ts = int(ts[s])
                d = datetime.fromtimestamp(day_ts, tz=timezone.utc).strftime("%Y-%m-%d")
                if d in dvol_map:
                    iv_open = dvol_map[d] / 100.0
                    band = hr.dvol_band(dvol_map[d])
                else:
                    # synthetic from 30d trailing realized vol
                    rv_window = px[max(0, s - 30 * 24):s]
                    rv = realized_vol_30d(rv_window)
                    iv_open = synthetic_iv(rv)
                    band = hr.dvol_band(iv_open * 100.0)

                # Replay this pair using simulator's pair lifecycle, but with
                # per-day implied vol = empirical DVOL or proxy that day.
                pair_result = replay_one_pair(
                    px, ts, dvol_map, s, PAIR_DAYS, BARRIER, PAYOUT,
                    NOTIONAL, RFR, SPREAD, sched_call, instrument,
                )
                if pair_result:
                    pair_result["dvol_band_at_open"] = band
                    pair_result["iv_open"] = iv_open
                    results.append(pair_result)
                    triggers_list.append(pair_result["triggers"])

            if not results:
                continue
            pnls = np.array([r["pnl_pair_life"] for r in results])
            triggers = np.array(triggers_list)
            wd["schedules"][sched_label] = {
                "n": len(results),
                "mean_pnl": float(pnls.mean()),
                "median_pnl": float(np.median(pnls)),
                "min_pnl": float(pnls.min()),
                "p05_pnl": float(np.percentile(pnls, 5)),
                "p95_pnl": float(np.percentile(pnls, 95)),
                "p_pnl_pos": float((pnls > 0).mean()),
                "mean_triggers": float(triggers.mean()),
                "median_triggers": float(np.median(triggers)),
                "p95_triggers": float(np.percentile(triggers, 95)),
                "max_triggers": int(triggers.max()),
                "worst_pair_pnl": float(pnls.min()),
                "worst_pair_start": results[int(np.argmin(pnls))]["start_date"],
            }

        # Render markdown table
        P(f"\n| Schedule | Mean P&L | Median | p05 | p95 | P[PnL>0] | Mean trigs | Worst week |")
        P(f"|---|---|---|---|---|---|---|---|")
        for k, v in wd["schedules"].items():
            P(f"| {k} | ${v['mean_pnl']:+,.0f} | ${v['median_pnl']:+,.0f} | "
              f"${v['p05_pnl']:+,.0f} | ${v['p95_pnl']:+,.0f} | {v['p_pnl_pos']*100:.0f}% | "
              f"{v['mean_triggers']:.1f} | ${v['worst_pair_pnl']:+,.0f} ({v['worst_pair_start']}) |")
        P("")
        out["windows"].append(wd)

        for k, v in wd["schedules"].items():
            print(f"  {k}: mean=${v['mean_pnl']:+,.0f}  "
                  f"median=${v['median_pnl']:+,.0f}  "
                  f"p05=${v['p05_pnl']:+,.0f}  "
                  f"P[+]={v['p_pnl_pos']*100:.0f}%  "
                  f"trigs={v['mean_triggers']:.1f}")

    out_dir = hr.OUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "stress_windows.json").write_text(json.dumps(out, indent=2))
    (out_dir / "stress_windows.md").write_text("\n".join(md_lines))
    print(f"\nWrote {(out_dir / 'stress_windows.json')}")
    print(f"Wrote {(out_dir / 'stress_windows.md')}")


def premium_for(schedule: str, dvol: float) -> float:
    """Per-side per-day premium under different schedules."""
    if schedule == "tiered_400_600_900":
        if dvol < 50:
            return 400.0
        if dvol < 65:
            return 600.0
        return 900.0
    if schedule == "tiered_with_stress_1100":
        if dvol < 50:
            return 400.0
        if dvol < 65:
            return 600.0
        if dvol < 80:
            return 900.0
        return 1_100.0
    if schedule == "flat_500_900":
        if dvol < 65:
            return 500.0
        return 900.0
    raise ValueError(schedule)


def replay_one_pair(
    px: np.ndarray, ts: np.ndarray, dvol_map: dict,
    start_idx: int, pair_days: int, barrier: float, payout: float,
    notional: float, rfr: float, spread_bps: float,
    schedule: str, instrument: str,
) -> dict | None:
    """One pair lifecycle, daily ±2% strangle, with per-day IV from DVOL
    (or synthetic if pre-2021-04). Premium under given schedule."""
    spot0 = px[start_idx]
    end_idx = min(start_idx + pair_days * 24, len(px) - 1)
    s_path = px[start_idx : end_idx + 1]
    t_unix = ts[start_idx : end_idx + 1]
    n_hours = len(s_path) - 1
    if n_hours < pair_days * 24 - 6:
        return None

    book = sim.HedgeBook()
    cash_out = 0.0
    cash_in = 0.0
    triggers = 0
    payouts = 0.0
    premium = 0.0
    initial_cost = 0.0

    product_obj = sim.Product(
        spot0=spot0, notional_per_side=notional, barrier_pct=barrier,
        max_days=pair_days, payout_per_trigger=payout, rfr=rfr,
        venue_spread_bps=spread_bps, premium_per_pair_day=0.0,
    )

    anchor_price = spot0
    for day in range(1, pair_days + 1):
        day_start_h = (day - 1) * 24
        day_end_h = min(day * 24, n_hours)
        day_ts = int(t_unix[day_start_h])
        d = datetime.fromtimestamp(day_ts, tz=timezone.utc).strftime("%Y-%m-%d")
        if d in dvol_map:
            dvol_today = dvol_map[d]
        else:
            rv_window = px[max(0, start_idx + day_start_h - 30 * 24):
                           start_idx + day_start_h]
            rv = realized_vol_30d(rv_window)
            dvol_today = synthetic_iv(rv) * 100.0
        sigma_day = dvol_today / 100.0
        rate_per_pair_day = premium_for(schedule, dvol_today) * 2.0
        # Pair opens at day-start; full daily premium charged
        premium += rate_per_pair_day

        anchor_price = s_path[day_start_h]
        cost = book.open_strangle(product_obj, sigma_day, anchor_price,
                                   day - 1.0, tenor_days=1)
        cash_out += cost
        if day == 1:
            initial_cost = cost

        cur_h = day_start_h
        anchor_price = s_path[cur_h]
        while cur_h < day_end_h:
            cur_h += 1
            cur_px = s_path[cur_h]
            move_pct = abs(cur_px / anchor_price - 1.0)
            if move_pct < barrier:
                continue
            triggers += 1
            payouts += payout
            now_day = cur_h / 24.0
            side_call = cur_px > anchor_price

            # Sell ITM leg
            cash = book.sell_first_inthemoney_leg(
                product_obj, sigma_day, cur_px, now_day, is_call=side_call,
            )
            cash_in += cash

            # Foxify closes both perps and reopens at new spot.
            # Atticus opens a fresh ±2% strangle and charges pro-rated
            # premium for the rest of the day.
            remaining_hours = max(0, day_end_h - cur_h)
            if remaining_hours > 0:
                new_cost = book.open_strangle(
                    product_obj, sigma_day, cur_px, now_day, tenor_days=1,
                )
                cash_out += new_cost
                premium += rate_per_pair_day * (remaining_hours / 24.0)

            anchor_price = cur_px

        # End-of-day: mark all surviving 1-day legs
        end_px = s_path[day_end_h]
        end_day = day_end_h / 24.0
        residual = book.mark_to_market(product_obj, sigma_day, end_px, end_day)
        cash_in += residual * (1 - product_obj.venue_spread_bps / 10_000.0)
        book.legs.clear()

    pnl = premium - payouts - cash_out + cash_in
    return {
        "start_date": datetime.fromtimestamp(int(t_unix[0]), tz=timezone.utc)
            .strftime("%Y-%m-%d"),
        "spot0": float(spot0),
        "triggers": triggers,
        "premium_collected": premium,
        "payouts_paid": payouts,
        "hedge_cash_out": cash_out,
        "hedge_cash_in": cash_in,
        "initial_hedge_cost": initial_cost,
        "pnl_pair_life": pnl,
    }


if __name__ == "__main__":
    main()
